### ISSUE TITLE
DiscordGameStatus has stopped working

### ISSUE THREAD

**Issue by Henlyson** [PotcFdk/DiscordGameStatus#10]
I have noticed that recently the script has stopped working, you can't even see the button anymore. I guess they have updated Discord, and the script needs to be updated, too :(

**Comment by PotcFdk** [comment]
You're right. I've checked it out some time ago and Discord has worsened the ease of coming up with good code to manipulate the UI.
I'll re-investigate this soon-ish.

**Comment by osuthailand** [comment]
I found out that token in Application tab is removed. That's why it's not working because it got no token to use

**Comment by osuthailand** [comment]
but you can use mobile view to get the token back!

**Comment by SuperOP535** [comment]
@osuthailand It's not about localStorage, that got "disabled" ages ago. It's about the UI change.

**Comment by kevin51jiang** [comment]
Any update?
