### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by TobiTenno** [PotcFdk/DiscordGameStatus#2]
👎 Setting it doesn't set my own status, which is visible from either the desktop app or from the user's profile.

**Comment by PotcFdk** [comment]
You can't see your own status. Have you checked your game status from another Discord user account?

**Comment by TobiTenno** [comment]
indeed.

**Comment by PotcFdk** [comment]
So you have clicked the icon, typed in some text, clicked OK, and the status does not update when looking at your profile from another user's account?
If that's the case, what browser and extension are you using? Can you provide version numbers?

**Comment by TobiTenno** [comment]
Chrome 56.0.2924.87 (64-bit), tampermonkey, dunno version number on that.

Yes, I've done that. I'll try again later.

**Comment by PotcFdk** [comment]
Please make sure that the DiscordGameStatus userscript is up to date (trigger an update check in Tampermonkey).

Next, [open Discord](https://discordapp.com/channels/@me) and press F12.
In the newly opened toolbar/console, click on the "Console" tab, scroll up to the beginning and see if there is a message that says something like
`[DiscordGameStatus] Found WebSocket object`

![screenshot](https://cloud.githubusercontent.com/assets/3160048/23143801/9b19b9ac-f7c3-11e6-9eb8-1709f5c5ee0b.png)


(If there is anything listed that has a red colored background and tells you about any kind of errors, something like this
![screenshot](https://cloud.githubusercontent.com/assets/3160048/23143782/862a8878-f7c3-11e6-8c6d-1f23a2bf8730.png)
please also tell that.)


You can press F12 again to close the the toolbar.

**Comment by PotcFdk** [comment]
I'll assume this is fixed. Feel free to add a new comment if it isn't.
