### ISSUE TITLE
Button panel overflow

### ISSUE THREAD

**Issue by Zaphox** [PotcFdk/DiscordGameStatus#3]
One of the last two commits introduced an issue where every second there are more and more Set Game Status buttons without an icon being added, slowly growing the button list until it covers the screen top to bottom.

https://h3.hawnutor.org/image/_4cYOVHz.png

Firefox 51.0.1
Greasemonkey 3.9
Windows 7

**Comment by PotcFdk** [comment]
Thanks for the report!
