### ISSUE TITLE
The script is loaded but the playing status is not displayed

### ISSUE THREAD

**Issue by unixfox** [PotcFdk/DiscordGameStatus#8]
Hello!

The playing status isn't displayed after setting the game name from the userscript. The script is correctly loaded:
![](https://i.imgur.com/Yhc4ySJ.png)

I'm using Firefox with Tampermonkey (I already tried with greasemonkey but that doesn't change).

**Comment by PotcFdk** [comment]
Fixed in 1.6.0.
